# Generated by Django 3.1.7 on 2022-12-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='userotp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user_otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
    ]
