# Generated by Django 3.1.7 on 2022-12-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20221208_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='user_otp',
        ),
    ]
